# Generated by Django 4.2.1 on 2023-09-07 05:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yangiliklar',
            name='desc_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='yangiliklar',
            name='desc_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='yangiliklar',
            name='desc_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='yangiliklar',
            name='title_en',
            field=models.CharField(max_length=233, null=True),
        ),
        migrations.AddField(
            model_name='yangiliklar',
            name='title_ru',
            field=models.CharField(max_length=233, null=True),
        ),
        migrations.AddField(
            model_name='yangiliklar',
            name='title_uz',
            field=models.CharField(max_length=233, null=True),
        ),
    ]
