# Generated by Django 4.2.1 on 2023-09-14 05:13

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aksiyodorlar',
            name='category',
        ),
        migrations.AddField(
            model_name='aksiyodorlar',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.categoy'),
        ),
    ]
