# Generated by Django 4.2.1 on 2023-06-24 06:29

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_banner_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='home.banner'),
        ),
    ]
