# Generated by Django 4.2.1 on 2023-06-24 09:20

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_ishlabchiqrish_jarayon_tanishuv'),
    ]

    operations = [
        migrations.AddField(
            model_name='ishlabchiqrish',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='home.ishlabchiqrish'),
        ),
        migrations.AddField(
            model_name='jarayon',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='home.jarayon'),
        ),
        migrations.AddField(
            model_name='tanishuv',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='home.tanishuv'),
        ),
    ]
