# Generated by Django 4.2.1 on 2023-06-24 09:54

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='home.homepage'),
        ),
    ]
