# Generated by Django 4.2.1 on 2023-06-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepage_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='desc_en',
            field=models.CharField(max_length=232, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='desc_ru',
            field=models.CharField(max_length=232, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='name_en',
            field=models.CharField(max_length=232, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='name_ru',
            field=models.CharField(max_length=232, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_en',
            field=models.CharField(max_length=232, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_ru',
            field=models.CharField(max_length=232, null=True),
        ),
        migrations.AddField(
            model_name='categoy',
            name='name_en',
            field=models.CharField(max_length=232, null=True),
        ),
        migrations.AddField(
            model_name='categoy',
            name='name_ru',
            field=models.CharField(max_length=232, null=True),
        ),
        migrations.AddField(
            model_name='ishlabchiqrish',
            name='desc_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ishlabchiqrish',
            name='desc_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ishlabchiqrish',
            name='title_en',
            field=models.CharField(max_length=232, null=True),
        ),
        migrations.AddField(
            model_name='ishlabchiqrish',
            name='title_ru',
            field=models.CharField(max_length=232, null=True),
        ),
        migrations.AddField(
            model_name='jarayon',
            name='desc_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jarayon',
            name='desc_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jarayon',
            name='title_en',
            field=models.CharField(max_length=232, null=True),
        ),
        migrations.AddField(
            model_name='jarayon',
            name='title_ru',
            field=models.CharField(max_length=232, null=True),
        ),
        migrations.AddField(
            model_name='sidecategory',
            name='name_en',
            field=models.CharField(max_length=232, null=True),
        ),
        migrations.AddField(
            model_name='sidecategory',
            name='name_ru',
            field=models.CharField(max_length=232, null=True),
        ),
        migrations.AddField(
            model_name='tanishuv',
            name='desc_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tanishuv',
            name='desc_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tanishuv',
            name='title_en',
            field=models.CharField(max_length=232, null=True),
        ),
        migrations.AddField(
            model_name='tanishuv',
            name='title_ru',
            field=models.CharField(max_length=232, null=True),
        ),
    ]
