# Generated by Django 4.2.1 on 2023-08-05 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_banner_desc_en_banner_desc_ru_banner_name_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoy',
            options={'verbose_name': 'Asosiy Kategoriya'},
        ),
    ]
