# Generated by Django 4.2.1 on 2023-08-07 07:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_banner_options_alter_categoy_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jarayon',
            options={'verbose_name': 'Yangilik', 'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='banner',
            name='desc_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='desc_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='desc_uz',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=232, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title_en',
            field=models.CharField(blank=True, max_length=232, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title_ru',
            field=models.CharField(blank=True, max_length=232, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title_uz',
            field=models.CharField(blank=True, max_length=232, null=True),
        ),
        migrations.AlterField(
            model_name='jarayon',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='jarayon',
            name='desc_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='jarayon',
            name='desc_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='jarayon',
            name='desc_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
