# Generated by Django 4.2.1 on 2023-08-08 05:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_jarayon_options_alter_banner_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoy',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jarayon',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jarayon',
            name='desc_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jarayon',
            name='desc_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jarayon',
            name='desc_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
