# Generated by Django 4.2.1 on 2023-08-10 05:03

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_categoy_slug_en_categoy_slug_ru_categoy_slug_uz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aksiyodorlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=232)),
                ('file', models.FileField(upload_to='media/pdf/%Y/%m/%d')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.categoy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
