# Generated by Django 4.2.1 on 2023-08-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_aksiyodorlar_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aksiyodorlar',
            name='category',
        ),
        migrations.AddField(
            model_name='aksiyodorlar',
            name='category',
            field=models.ManyToManyField(to='home.categoy'),
        ),
    ]
