# Generated by Django 4.2.1 on 2023-08-19 09:50

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_aksiyodorlar_category_aksiyodorlar_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raxbariyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=232)),
                ('title_uz', models.CharField(max_length=232, null=True)),
                ('title_en', models.CharField(max_length=232, null=True)),
                ('title_ru', models.CharField(max_length=232, null=True)),
                ('image', models.ImageField(upload_to='raxbarlar/%Y/%m')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.categoy')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='home.raxbariyat')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
