# Generated by Django 4.2.1 on 2023-08-21 07:08

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_raxbariyat_desc_raxbariyat_desc_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raxbariyat',
            name='lavozim',
            field=models.CharField(default='', max_length=232),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raxbariyat',
            name='lavozim_en',
            field=models.CharField(max_length=232, null=True),
        ),
        migrations.AddField(
            model_name='raxbariyat',
            name='lavozim_ru',
            field=models.CharField(max_length=232, null=True),
        ),
        migrations.AddField(
            model_name='raxbariyat',
            name='lavozim_uz',
            field=models.CharField(max_length=232, null=True),
        ),
        migrations.CreateModel(
            name='RaxbariyatTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', ckeditor.fields.RichTextField()),
                ('desc_uz', ckeditor.fields.RichTextField(null=True)),
                ('desc_en', ckeditor.fields.RichTextField(null=True)),
                ('desc_ru', ckeditor.fields.RichTextField(null=True)),
                ('raxbariyat', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raxbariyats', to='home.raxbariyat')),
            ],
        ),
    ]
