# Generated by Django 4.2.1 on 2023-08-21 09:33

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_raxbariyat_lavozim_raxbariyat_lavozim_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raxbariyat',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='raxbariyat',
            name='desc_en',
        ),
        migrations.RemoveField(
            model_name='raxbariyat',
            name='desc_ru',
        ),
        migrations.RemoveField(
            model_name='raxbariyat',
            name='desc_uz',
        ),
        migrations.CreateModel(
            name='Texnika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=232)),
                ('title_uz', models.CharField(max_length=232, null=True)),
                ('title_en', models.CharField(max_length=232, null=True)),
                ('title_ru', models.CharField(max_length=232, null=True)),
                ('madel', models.CharField(max_length=232)),
                ('madel_uz', models.CharField(max_length=232, null=True)),
                ('madel_en', models.CharField(max_length=232, null=True)),
                ('madel_ru', models.CharField(max_length=232, null=True)),
                ('image', models.ImageField(upload_to='raxbarlar/%Y/%m')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.categoy')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='home.texnika')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
