# Generated by Django 4.2.1 on 2023-08-25 12:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_raxbariyat_desc_remove_raxbariyat_desc_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='texnika',
            name='desc',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='texnika',
            name='desc_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='texnika',
            name='desc_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='texnika',
            name='desc_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
