# Generated by Django 4.2.1 on 2023-09-06 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_texnika_desc_texnika_desc_en_texnika_desc_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TexnikaTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=233)),
                ('kub', models.CharField(max_length=233)),
                ('sigim', models.CharField(max_length=233)),
                ('texnika', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='texnikala', to='home.texnika')),
            ],
        ),
    ]
