# Generated by Django 4.2.1 on 2023-09-07 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_texnikatable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jarayon',
            options={'verbose_name': 'Jarayon(Yangilik)', 'verbose_name_plural': 'Jarayonlar(Yangiliklar)'},
        ),
    ]
