# Generated by Django 4.2.1 on 2023-09-09 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_texnikatable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jarayon',
            options={'verbose_name': 'Jarayon(Yangilik)', 'verbose_name_plural': 'Jarayonlar(Yangiliklar)'},
        ),
        migrations.RemoveField(
            model_name='aksiyodorlar',
            name='category',
        ),
        migrations.AddField(
            model_name='aksiyodorlar',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.categoy'),
            preserve_default=False,
        ),
    ]
