# Generated by Django 4.2.1 on 2023-09-09 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_jarayon_options_remove_aksiyodorlar_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aksiyodorlar',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.categoy'),
        ),
    ]
