# Generated by Django 4.2.1 on 2023-09-07 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_jarayon_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aksiyodorlar',
            name='category',
        ),
        migrations.AddField(
            model_name='aksiyodorlar',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.categoy'),
            preserve_default=False,
        ),
    ]
