# Generated by Django 4.2.1 on 2023-09-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_aksiyodorlar_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aksiyodorlar',
            name='category',
        ),
        migrations.AddField(
            model_name='aksiyodorlar',
            name='category',
            field=models.ManyToManyField(to='home.categoy'),
        ),
    ]
