# Generated by Django 4.2.1 on 2023-08-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=233)),
                ('name_uz', models.CharField(max_length=233, null=True)),
                ('name_en', models.CharField(max_length=233, null=True)),
                ('name_ru', models.CharField(max_length=233, null=True)),
                ('image', models.ImageField(upload_to='prodCategories/%Y/%m/%d/')),
                ('slug', models.SlugField()),
                ('slug_uz', models.SlugField(null=True)),
                ('slug_en', models.SlugField(null=True)),
                ('slug_ru', models.SlugField(null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
