# Generated by Django 4.2.1 on 2023-08-14 10:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productcategories_parent_products_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='desc_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='desc_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='desc_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='name_en',
            field=models.CharField(max_length=233, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='name_ru',
            field=models.CharField(max_length=233, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='name_uz',
            field=models.CharField(max_length=233, null=True),
        ),
    ]
